services:
  # The PostgreSQL Database for the game
  - type: pserv
    name: gwent-db
    plan: free

  # The Backend Game Server (from the /server directory)
  - type: web
    name: gwent-server
    plan: free
    env: docker
    repo: https://github.com/DJ-EJ-L/gwent-classic.git
    dockerContext: ./server
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gwent-db
          property: connectionString
      - key: PORT
        value: 5000

  # The Frontend Web Client (from the /web directory)
  - type: web
    name: gwent-web
    plan: free
    env: docker
    repo: https://github.com/DJ-EJ-L/gwent-classic.git
    dockerContext: ./web
    dockerfilePath: ./web/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: gwent-server
          property: host # Provides the hostname e.g. gwent-server.onrender.com
      - key: PORT
        value: 3000
