databases:
  - name: gwent-db
    plan: free

services:
  # The Backend Game Server
  - type: web
    name: gwent-server
    runtime: docker
    repo: https://github.com/DJ-EJ-L/gwent-classic-mp.git
    plan: free
    dockerContext: ./server
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gwent-db
          property: connectionString
      - key: PORT
        value: 5000

  # The Frontend Web Client
  - type: web
    name: gwent-web
    runtime: docker
    repo: https://github.com/DJ-EJ-L/gwent-classic-mp.git
    plan: free
    dockerContext: ./web
    dockerfilePath: ./web/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: gwent-server
          property: host
      - key: PORT
        value: 3000
